# Generated by Django 5.2.6 on 2025-09-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasoreceta',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo_coccion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='cantidad',
            field=models.CharField(default='al gusto', max_length=100),
        ),
    ]
