# Generated by Django 5.2.6 on 2025-09-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion2', '0002_remove_pasoreceta_creado_remove_receta_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo_coccion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.IntegerField(),
        ),
    ]
