# Generated by Django 5.2.6 on 2025-09-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion2', '0003_alter_receta_nombre_alter_receta_tiempo_coccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
